### ISSUE TITLE
1.1.4 (manuscript resubmission) checklist

### ISSUE THREAD

**Issue by mitchellmanware** [NIEHS/amadeus#134]
- [x] https://github.com/NIEHS/amadeus/issues/130
  - https://github.com/NIEHS/amadeus/commit/ca7aef29566a66cfc27fda98e1e63a446027ee9e
- [x] https://github.com/NIEHS/amadeus/issues/133
  - https://github.com/NIEHS/amadeus/commit/7ac41bd07582bfba24d33e9c544de682b5e61bce 
- [x] https://github.com/NIEHS/amadeus/issues/132
  - https://github.com/NIEHS/amadeus/commit/3709bc24007898d876234f24c215a58c564abcce
- [x] https://github.com/NIEHS/amadeus/issues/135
  - https://github.com/NIEHS/amadeus/commit/ea6fb80e17b256aaedf5c16aa92318b01fe763de
- [x] Remove the figure on contributing. Move contributing down towards the bottom of the readme as this isn't typically so prominent. 
  - https://github.com/NIEHS/amadeus/commit/ab844fec95df2879cca7a5563d5ec810beb7481f
- [x] Add a link and mention to CHORDS. Currently the connection to CHORDS via the dual hex is unclear. 
  - https://github.com/NIEHS/amadeus/commit/21baaa80d4d5266fb23350cc1f4a1793395c395f
